import type { DashboardData, Listing } from "./types";

const observedAt = "2026-08-25T09:00:00+02:00";

const base = {
  source: "demo-source",
  first_seen_at: observedAt,
  last_seen_at: observedAt,
  status_changed_at: observedAt,
  seller_name: null,
  agency_name: null,
  notes: null,
  observed_at: observedAt,
  currency: "EUR",
  price_basis: "total",
  precise_area_m2: null,
  area_basis: "advertised area",
  bathrooms: 1,
  total_floors: 6,
  year_built: null,
  building_condition: "Good condition",
  parking_spaces: null,
  garage: false,
  distance_from_sea_m: null,
  furnished: true,
  elevator: true,
  public_contact: null,
  source_published_at: "2026-08-24",
  source_modified_at: "2026-08-25",
  description_raw: "Synthetic portfolio data. No production listing or advertiser data is included.",
  ambiguity_flags: [] as string[],
  extraction_confidence: "high" as const,
  explanation: "Demo score based on price, freshness and property attributes.",
  score_model_version: "demo-v1",
  is_favorite: false,
  private_notes: null,
  annotation_updated_at: null,
  status_history: [{
    changed_at: observedAt,
    old_status: null,
    new_status: "New",
    reason: "Synthetic portfolio dataset",
  }],
};

const rows: Partial<Listing>[] = [
  {
    id: "demo-001",
    source_listing_id: "demo-001",
    title: "Two-bedroom apartment near the city centre",
    normalized_location: "Bar Centar",
    source_location_raw: "Centar",
    price_value: 128000,
    price_raw: "€128,000",
    advertised_area_m2: 64,
    area_used_for_ppsqm_m2: 64,
    calculated_price_per_m2: 2000,
    bedrooms: 2,
    floor: "3",
    parking: true,
    sea_view: false,
    new_construction: false,
    seller_type: "agency",
    agency_name: "Demo Agency",
    classification: "Attractive",
    total_score: 58,
    current_status: "Review",
    clean_baseline_eligible: true,
    possible_duplicate: false,
  },
  {
    id: "demo-002",
    source: "second-demo-source",
    source_listing_id: "demo-002",
    title: "One-bedroom apartment with sea view",
    normalized_location: "Šušanj",
    source_location_raw: "Šušanj",
    price_value: 92000,
    price_raw: "€92,000",
    advertised_area_m2: 46,
    area_used_for_ppsqm_m2: 46,
    calculated_price_per_m2: 2000,
    bedrooms: 1,
    floor: "4",
    parking: false,
    sea_view: true,
    new_construction: false,
    seller_type: "owner",
    classification: "Attractive",
    total_score: 54,
    current_status: "Watch",
    clean_baseline_eligible: true,
    possible_duplicate: true,
  },
  {
    id: "demo-003",
    source_listing_id: "demo-003",
    title: "New-build apartment with parking",
    normalized_location: "Bjeliši",
    source_location_raw: "Bjeliši",
    price_value: 108000,
    price_raw: "€108,000",
    advertised_area_m2: 50,
    area_used_for_ppsqm_m2: 50,
    calculated_price_per_m2: 2160,
    bedrooms: 1,
    floor: "2",
    parking: true,
    sea_view: false,
    new_construction: true,
    seller_type: "investor",
    classification: "Interesting",
    total_score: 46,
    current_status: "New",
    clean_baseline_eligible: true,
    possible_duplicate: false,
  },
];

const listings = rows.map((row) => ({
  ...base,
  canonical_url: `https://example.com/listings/${row.source_listing_id}`,
  price_history: [{
    observed_at: observedAt,
    price_value: row.price_value ?? null,
    price_basis: "total",
    currency: "EUR",
    previous_price: null,
    change_amount: null,
    change_percent: null,
  }],
  ...row,
})) as Listing[];

export const previewData: DashboardData = {
  generated_at: observedAt,
  latest_scan: {
    source: "demo-source",
    started_at: observedAt,
    listings_discovered: 42,
    pages_successful: 42,
    pages_failed: 0,
    authenticated: true,
  },
  listings,
  scan_history: [{
    source: "demo-source",
    started_at: observedAt,
    listings_discovered: 42,
    pages_successful: 42,
    pages_failed: 0,
    authenticated: true,
  }],
  changes: [{
    listing_id: "demo-001",
    source: "demo-source",
    source_listing_id: "demo-001",
    title: "Two-bedroom apartment near the city centre",
    normalized_location: "Bar Centar",
    observed_at: observedAt,
    event_type: "price_reduced",
    previous_price: 132000,
    current_price: 128000,
    change_amount: -4000,
    change_percent: -3.03,
    changed_fields: ["price"],
  }],
  duplicates: [{
    id: "demo-duplicate-001",
    listing_id_a: "demo-001",
    source_a: "demo-source",
    source_listing_id_a: "demo-001",
    listing_id_b: "demo-002",
    source_b: "second-demo-source",
    source_listing_id_b: "demo-002",
    confidence_score: 0.91,
    same_phone: false,
    same_area: false,
    same_location: false,
    same_bedrooms: false,
    same_floor: false,
    similar_price: true,
    description_similarity: 0.72,
    photo_similarity: null,
    reason: "Synthetic cross-source review candidate",
    review_status: "Needs Review",
  }],
  duplicate_refresh: {
    trigger_source: "scheduled",
    started_at: observedAt,
    finished_at: observedAt,
    candidates_considered: 8,
    candidates_inserted: 1,
    candidates_updated: 7,
  },
  saved_searches: [],
  dataMode: "preview",
};
